version: "3.5"
services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - youteller
    ports:
      - 83:8080
    depends_on:
      - db
  db:
    image: mariadb
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: .db.env
    networks:
      - youteller
    volumes:
      - firefly_iii_db:/var/lib/mysql
  youteller-api:
    container_name: youteller-api
    env_file: ./youteller-api/.env
    volumes:
      - ./youteller-api:/opt/app/youteller-api
      - ./cursors:/opt/app/cursors
    networks:
      - youteller
    build:
      context: .
      dockerfile: ./youteller-api/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - app
      - db
    restart: always
networks:
  youteller:
    name: youteller
volumes:
  firefly_iii_upload:
  firefly_iii_db: